-- Schema for the intentionally vulnerable DAST test target.
-- Compatible with PostgreSQL and H2 (PostgreSQL mode).

DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS api_clients;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(255),
    password     VARCHAR(255),
    email        VARCHAR(255),
    role         VARCHAR(64),
    ssn          VARCHAR(32),
    credit_card  VARCHAR(32),
    api_key      VARCHAR(128),
    reset_token  VARCHAR(128),
    is_admin     BOOLEAN DEFAULT FALSE,
    balance      NUMERIC(14,2) DEFAULT 0,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT,
    account_number VARCHAR(64),
    balance        NUMERIC(14,2) DEFAULT 0,
    type           VARCHAR(32)
);

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(2000),
    price       NUMERIC(12,2),
    owner_id    BIGINT,
    stock       INT DEFAULT 0
);

CREATE TABLE orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    product_id BIGINT,
    quantity   INT,
    total      NUMERIC(12,2),
    status     VARCHAR(32)
);

CREATE TABLE documents (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id  BIGINT,
    filename  VARCHAR(512),
    filepath  VARCHAR(1024),
    content   VARCHAR(4000),
    is_public BOOLEAN DEFAULT FALSE
);

CREATE TABLE comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author     VARCHAR(255),
    body       VARCHAR(4000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id    BIGINT,
    recipient_id BIGINT,
    subject      VARCHAR(512),
    body         VARCHAR(4000),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE api_clients (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     VARCHAR(128),
    client_secret VARCHAR(128),
    scopes        VARCHAR(512),
    owner_id      BIGINT
);

CREATE TABLE audit_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action     VARCHAR(255),
    username   VARCHAR(255),
    ip         VARCHAR(64),
    detail     VARCHAR(2000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
